kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ubuntu:latest
  commands:
    - echo '========Install the necessary environment========'
    - apt update && apt install -y curl gcc git libwebkit2gtk-4.0-dev libappindicator3-dev
    - echo '========Install the Rust toolchain========'
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
    - echo '========Compile the Neutauri binary========'
    - $HOME/.cargo/bin/cargo build --release --bin neutauri_runtime
    - $HOME/.cargo/bin/cargo build --release --bin neutauri_bundler

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.186526.xyz
    files:
      - ./target/release/neutauri_bundler
    checksum:
      - md5
      - sha256
  when:
    event: 
      - tag