kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  commands:
    - cargo build --release --bin neutauri_runtime
    - cargo build --release --bin neutauri_bundler

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.186526.xyz
    files:
      - ./target/release/neutauri_bundler
    checksum:
      - md5
      - sha256
  when:
    event: 
      - tag