[package]
edition = "2021"
name = "neutauri_runtime"
version = "0.1.0"

[dependencies]
bincode = "1.3"
brotli = "3.3"
serde = {version = "1.0", features = ["derive"]}
wry = {version = "0.15", default-features = false, features = ["protocol", "tray", "gtk-tray", "transparent", "fullscreen"]}

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = ""
FileVersion = ""
LegalCopyright = ""
OriginalFilename = ""
ProductName = ""
ProductVersion = ""
