[package]
edition = "2021"
name = "neutauri_bundler"
version = "0.1.0"

[dependencies]
bincode = "1.3"
brotli = "3.3"
image = "0.23"
new_mime_guess = "4.0"
serde = {version = "1.0", features = ["derive"]}
toml = "0.5"
wry = "0.12"

[profile.release.package.wry]
debug = true
debug-assertions = true