[package]
edition = "2021"
name = "neutauri_bundler"
version = "0.1.0"

[dependencies]
bincode = "1.3"
brotli = "3.3"
gumdrop = "0.8"
image = "0.24"
new_mime_guess = "4.0"
serde = {version = "1.0", features = ["derive"]}
toml = "0.5"
wry = {version = "0.15", features = ["devtools"]}
